# Generated by pkg-ext
# flake8: noqa
from path_sync import config
from path_sync import copy
from path_sync import dep_update

VERSION = "0.3.5"
__all__ = [
    "config",
    "copy",
    "dep_update",
]
