# Generated by pkg-ext
from path_sync._internal.models import AutoMergeConfig as _AutoMergeConfig
from path_sync._internal.models import Destination as _Destination
from path_sync._internal.models import HeaderConfig as _HeaderConfig
from path_sync._internal.models import MergeMethod as _MergeMethod
from path_sync._internal.models import PathMapping as _PathMapping
from path_sync._internal.models import PRDefaults as _PRDefaults
from path_sync._internal.models import SrcConfig as _SrcConfig
from path_sync._internal.models import SyncMode as _SyncMode

AutoMergeConfig = _AutoMergeConfig
Destination = _Destination
HeaderConfig = _HeaderConfig
MergeMethod = _MergeMethod
PRDefaults = _PRDefaults
PathMapping = _PathMapping
SrcConfig = _SrcConfig
SyncMode = _SyncMode
